<?php

namespace App\Controller;

use App\Entity\DocElectricite;
use App\Entity\Electricite;
use App\Form\DocElectriciteType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Exception;

/**
 * @Route("/doc/electricite")
 */
class DocElectriciteController extends AbstractController
{

    /**
     * @Route("/new/{electricite}", name="doc_electricite_new", methods={"GET","POST"})
     * @param Electricite $electricite
     * @param EntityManagerInterface $manager
     * @param Request $request
     * @return Response
     * @throws Exception
     */
    public function new(Electricite $electricite,EntityManagerInterface $manager,Request $request): Response
    {
        $docElectricite = new DocElectricite();
        $form = $this->createForm(DocElectriciteType::class, $docElectricite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $docElectricite->setElectricite($electricite);

            $file = $docElectricite->getDocFilename();
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            $file->move(
                $this->getParameter('upload_directory'),
                $fileName);
           $docElectricite->setDocFilename($fileName);
            $manager->persist($docElectricite);
            $manager->flush();

            return $this->redirectToRoute('home',['rubrique' => 'electricite']);
        }

        return $this->render('doc_electricite/new.html.twig', [
            'doc_electricite' => $docElectricite,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName(): string
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid('',true));
    }


    /**
     * @Route("/{id}/edit", name="doc_electricite_edit", methods={"GET","POST"})
     * @param Request $request
     * @param DocElectricite $docElectricite
     * @return Response
     */
    public function edit(Request $request, DocElectricite $docElectricite): Response
    {
        $form = $this->createForm(DocElectriciteType::class, $docElectricite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('home',['rubrique' => 'electricite']);
        }

        return $this->render('doc_electricite/edit.html.twig', [
            'doc_electricite' => $docElectricite,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="doc_electricite_delete", methods={"DELETE"})
     * @param Request $request
     * @param DocElectricite $docElectricite
     * @return Response
     */
    public function delete(Request $request, DocElectricite $docElectricite): Response
    {
        if ($this->isCsrfTokenValid('delete'.$docElectricite->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($docElectricite);
            $entityManager->flush();
        }

        return $this->redirectToRoute('home',['rubrique' => 'electricite']);
    }
}
