<?php

namespace App\Controller;

use App\Entity\DocOutillage;
use App\Entity\Outillage;
use App\Form\DocOutillageType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Exception;

/**
 * @Route("/doc/outillage")
 */
class DocOutillageController extends AbstractController
{

    /**
     * @Route("/new/{outillage}", name="doc_outillage_new", methods={"GET","POST"})
     * @param Outillage $outillage
     * @param EntityManagerInterface $manager
     * @param Request $request
     * @return Response
     * @throws Exception
     */
    public function new(Outillage $outillage,EntityManagerInterface $manager,Request $request): Response
    {
        $docOutillage = new DocOutillage();
        $form = $this->createForm(DocOutillageType::class, $docOutillage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $docOutillage->setOutillage($outillage);

            $file = $docOutillage->getDocFilename();
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            $file->move(
                $this->getParameter('upload_directory'),
                $fileName);
           $docOutillage->setDocFilename($fileName);
            $manager->persist($docOutillage);
            $manager->flush();

            return $this->redirectToRoute('home',['rubrique' => 'outillage']);
        }

        return $this->render('doc_outillage/new.html.twig', [
            'doc_outillage' => $docOutillage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName(): string
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid('',true));
    }


    /**
     * @Route("/{id}/edit", name="doc_outillage_edit", methods={"GET","POST"})
     * @param Request $request
     * @param DocOutillage $docOutillage
     * @return Response
     */
    public function edit(Request $request, DocOutillage $docOutillage): Response
    {
        $form = $this->createForm(DocOutillageType::class, $docOutillage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('home',['rubrique' => 'outillage']);
        }

        return $this->render('doc_outillage/edit.html.twig', [
            'doc_outillage' => $docOutillage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="doc_outillage_delete", methods={"DELETE"})
     * @param Request $request
     * @param DocOutillage $docOutillage
     * @return Response
     */
    public function delete(Request $request, DocOutillage $docOutillage): Response
    {
        if ($this->isCsrfTokenValid('delete'.$docOutillage->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($docOutillage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('home',['rubrique' => 'outillage']);
    }
}
